name: Run integration tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        environment-file: environment.yml
    - name: Install dependencies
      run: |
        conda activate test
        pip install .[testing]
    - name: Run the integration test
      run: |
        conda activate test
        tracy --version
        bowtie2 --version
        samtools --version
        covid-spike-classification -s --silence-warnings tests/data
        pytest --override-ini='python_files=integration_*.py' --override-ini='python_functions=integration_*'

