name: Run integration tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    defaults:
      run:
        shell: bash -l {0}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          environment-file: environment.yml
    - name: Install dependencies
      run: |
        conda activate test
        pip install .[testing]
    - name: Test with pytest
      run: |
        pytest --override-ini='python_files=integration_*.py' --override-ini='python_functions=integration_*'

