name: Run integration tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Set up conda
      run: bash
        conda init bash
    - name: Install dependencies
      run: bash
        source ~/.bashrc
        conda env create -n csc -f environment.yml
        conda activate csc
        pip install .[testing]
    - name: Test with pytest
      run: bash
        source ~/.bashrc
        pytest --override-ini='python_files=integration_*.py' --override-ini='python_functions=integration_*'

